image: fommil/docker-openjdk-sbt:latest
cache:
  paths:
    - project/.sbt
variables:
  SBT_TASK_LIMIT: "4"
  COURSIER_CACHE: "project/.sbt/coursier"

stages:
  - build
  - deploy

build_job:
  stage: build
  except:
    - master
  script:
    - sbt ";scalafmt::test ;test:scalafmt::test ;jmh:scalafmt::test ;sbt:scalafmt::test ;headerCheck ;test:headerCheck ;jmh:headerCheck"
    - sbt ";+test:compile ;+doc";
    - sbt "+test"

deploy_job:
  only:
    - master
  except:
    - tags
  stage: deploy
  script:
    - sbt "+publish"
