image: fommil/docker-openjdk-sbt:latest
cache:
  paths:
    - project/.sbt
variables:
  SBT_TASK_LIMIT: "4"
  COURSIER_CACHE: "project/.sbt/coursier"

stages:
  - build
  - deploy

build_job:
  stage: build
  except:
    - master
  script:
    - if $(git grep -qE "TODO|FIXME" *) ; then
        echo "Please remove TODO or FIXME." ;
        exit 1 ;
      fi
    - sbt ";checks ;+test:compile ;+doc ;+test"

deploy_job:
  only:
    - master
  except:
    - tags
  stage: deploy
  script:
    - sbt "+publish"
