language: scala
jdk:
  - openjdk8

matrix:
  include:
  - os: linux
  - os: osx
    env: JDK="adopt@1.8.0-222"
    language: bash
    before_script:
    - wget "https://raw.githubusercontent.com/DanySK/Gravis-CI/e3f0fc509abd9b55/.install-jdk-travis.sh"
    - source .install-jdk-travis.sh
  - name: lint
    script:
    - if $(git grep -qE "TODO|FIXME" *) ; then
        echo "Please remove TODO or FIXME." ;
        exit 1 ;
      fi
    - sbt lint
  allow_failures:
  - name: lint # TODO fix all warnings

script:
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/53f1edc685d8f269ac5513/sbt && chmod +x ./sbt
  - ./sbt ";+check ;+cpl ;+test"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier

notifications:
  email: false
