language: scala
jdk:
  - openjdk8

matrix:
  include:
  - scala: 2.12.8
  - scala: 2.13.0

script:
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/53f1edc685d8f269ac5513/sbt && chmod +x ./sbt
  - ./sbt "++${TRAVIS_SCALA_VERSION}" compile

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier

notifications:
  email: false
